version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    working_directory: ~/github.com/reillywatson/enumcover
    steps:
      - checkout
      - run: go test -race -coverprofile=coverage.txt -covermode=atomic
      - run: bash <(curl -s https://codecov.io/bash)
